import type { Metadata } from 'next'
import '@/app/globals.css'
import { ThemeModeScript, Flowbite } from 'flowbite-react'
import theme from '@/flowbite-theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <Flowbite theme={{ theme }}>
        <body className="antialiased">{children}</body>
      </Flowbite>
    </html>
  )
}
