import type { Metadata } from "next"
import localFont from "next/font/local"
import "@/app/globals.css"
import { ThemeModeScript, Flowbite } from "flowbite-react"
import theme from '@/flowbite-theme'
import { SessionProvider } from "next-auth/react"
import { Session } from "next-auth"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
  session: Session
}

export default function RootLayout({
  children,
  session
}: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <Flowbite theme={{theme}}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SessionProvider session={session}>
            {children}
          </SessionProvider>
        </body>
      </Flowbite>
    </html>
  )
}
