import type { Metadata } from 'next'
import '@/app/globals.css'
import { ThemeModeScript, Flowbite } from 'flowbite-react'
import theme from '@/flowbite-theme'
import { SessionProvider } from 'next-auth/react'
import { Session } from 'next-auth'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
  session: Session
}

export default function RootLayout({ children, session }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <Flowbite theme={{ theme }}>
        <SessionProvider session={session}>
          <body className="antialiased">{children}</body>
        </SessionProvider>
      </Flowbite>
    </html>
  )
}
